name: 000-kubeflow
namespace: argocd
additionalLabels: {}
additionalAnnotations: {}
finalizers:
  - resources-finalizer.argocd.argoproj.io
project: default
chart: kubeflow-core
destination:
  server: https://kubernetes.default.svc
  namespace: argocd
syncPolicy:
  automated:
    prune: false
    selfHeal: false
